### ISSUE TITLE
returning pandas dataframe from task results in ValueError

### ISSUE THREAD

**Issue by johnny-smitherson** [hyperdiv/hyperdiv#18]
Pandas Dataframe has a quirk where if you write `if df:` it errors out with this error:

```
2024-02-24 22:41:14     Traceback (most recent call last):
2024-02-24 22:41:14       File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/components/task.py", line 38, in run_task
2024-02-24 22:41:14         result_callback(error=str(e))
2024-02-24 22:41:14       File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/components/task.py", line 200, in result_callback
2024-02-24 22:41:14         self.result = result
2024-02-24 22:41:14       File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/prop.py", line 51, in __set__
2024-02-24 22:41:14         return StateAccessFrame.current().update_state(component._key, self.name, value)
2024-02-24 22:41:14       File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/frame.py", line 200, in update_state
2024-02-24 22:41:14         if updated:
2024-02-24 22:41:14       File "/opt/pypy/lib/pypy3.10/site-packages/pandas/core/generic.py", line 1576, in __nonzero__
2024-02-24 22:41:14         raise ValueError(
2024-02-24 22:41:14     ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

This error happens when you return a dataframe from a sync task.

I think this also happens when you place a dataframe in a state variable.

Workaround in the application: wrap all return value dataframes in 1-tuples, or dicts, or pickle them.

Fix in the library: replacing that `if updated` with `if updated is not None` or `if bool(updated):` or something like that would cause problems when the task actually wants to return `None` or `0` or some other false value - so this might require some refactoring to wrap the value in a cell/1-tuple and/or store more context in the runner

**Comment by mariusnita** [comment]
Fix will be in next release.
