### ISSUE TITLE
(pypy3.10) docs: ModuleNotFoundError: No module named '_symtable'

### ISSUE THREAD

**Issue by johnny-smitherson** [hyperdiv/hyperdiv#5]
Tried running docs website with pypy 3.10 interpreter, got this error

```
$ docker run -it pypy bash
root@827a861ed733:/# pip install hyperdiv
Collecting hyperdiv
...
root@827a861ed733:/# hyperdiv docs
Traceback (most recent call last):
  File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/hyperdiv-docs/start.py", line 2, in <module>
    from hyperdiv_docs.main import main
  File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/hyperdiv-docs/hyperdiv_docs/main.py", line 3, in <module>
    from .menu import menu
  File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/hyperdiv-docs/hyperdiv_docs/menu.py", line 18, in <module>
    from .pages.reference.components import components
  File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/hyperdiv-docs/hyperdiv_docs/pages/reference/components.py", line 6, in <module>
    from ...extractor.main import extract
  File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/hyperdiv-docs/hyperdiv_docs/extractor/main.py", line 7, in <module>
    from .extractor import Extractor
  File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/hyperdiv-docs/hyperdiv_docs/extractor/extractor.py", line 26, in <module>
    from .top_level_docs import get_top_level_docs
  File "/opt/pypy/lib/pypy3.10/site-packages/hyperdiv/hyperdiv-docs/hyperdiv_docs/extractor/top_level_docs.py", line 24, in <module>
    import symtable
  File "/opt/pypy/lib/pypy3.10/symtable.py", line 3, in <module>
    import _symtable
ModuleNotFoundError: No module named '_symtable'
```

this is because they have their own parser and tooling, incompatible with cpython:

- https://doc.pypy.org/en/latest/parser.html
- https://foss.heptapod.net/pypy/pypy/-/blob/branch/py3.10/pypy/interpreter/astcompiler/symtable.py?ref_type=heads

The example apps work fine with this interpreter, this seems to be only a problem with docs generation.

**Comment by mariusnita** [comment]
Interesting, thanks! I can fix this particular issue by avoiding to import `_symtable` when running the docs app. That import is needed when building the PyPI bundle, but not strictly needed at runtime. The `extractor` piece that analyzes the hyperdiv repo to generate docs metadata should probably be a separate tool.

Thanks for trying it with pypy.

**Comment by mariusnita** [comment]
I removed the dependency on `_symtable` in v0.1.2, although I haven't tested the docs app on pypy.
